config/routes.rb
UnclaimedMoney::Application.routes.draw do
  match "/auth/:provider/callback" => "home#oauth_callback"
  match 'search' => "home#search"
  match "/logout" => "home#logout"
  match "tasks" => 'home#tasks', as: 'add_tasks'

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :setup_session_user
  before_filter :merge_params_to_session, :except => [:logout]
  before_filter :setup_myusa_client, :except => [:logout]
  before_filter :setup_myusa_access_token, :except => [:logout]

  def search
    unless params[:last_name].blank?
      Headless.new.start if Rails.env == 'production'
      @fdic_search = FdicSearch.search_for(params[:last_name])
      @pbgc_search = PbgcSearch.search_for(params[:last_name], {:page => params[:page] || 1})
      @hud_search = HudSearch.search_for(params[:last_name])    
      #@ca_search = CaUnclaimedProperty.new(params[:last_name]) if params['states'] && params['states'].include?('California')
      #@md_search = MdUnclaimedProperty.new(params[:last_name]) if params['states'] && params['states'].include?('Maryland')
    
      @has_results = true if @fdic_search[:total] > 0 or 
                             @pbgc_search[:total] > 0 or 
                             @hud_search[:total] > 0
                             #@ca_search && @ca_search.total or 
                             #@md_search && @md_search.total
    end
  end

  def logout
    reset_session
    @myusa_access_token = nil

    redirect_to root_url
  end

  def oauth_callback
    auth = request.env["omniauth.auth"]
    session[:user] = auth.extra.raw_info.to_hash
    session[:token] = auth.credentials.token
    if request.env['action_dispatch.request.unsigned_session_cookie']['omniauth.origin']
      if request.env['omniauth.params']['modal']
        flash[request.env['omniauth.params']['modal']] = true
        flash[:success] = "You are now logged in to MyUSA and may add this item to your task list."
        redirect_to "#{request.env['action_dispatch.request.unsigned_session_cookie']['omniauth.origin']}##{request.env['omniauth.params']['modal']}"
      else
        redirect_to request.env['action_dispatch.request.unsigned_session_cookie']['omniauth.origin']
      end
    else
      redirect_to action:'index'
    end
  end

  def tasks
    if session[:user] != {} && @myusa_access_token
      tasks = create_tasks

      if tasks.status == 200
        flash[params[:modal]] = true
        flash[:success] = "Tasks saved to your MyUSA profile"
        back_to_search = "#{request.env['HTTP_REFERER']}##{params[:modal]}"
        redirect_to back_to_search
      else
        flash[:alert] = JSON.parse(response.body)["message"]
        redirect_to :back
      end
    else
      redirect_to "/auth/myusa?modal=#{params[:modal]}"
    end
  end
  
  private
  
  def setup_session_user
    session[:user] = {} if session[:user].nil?
  end
  
  def merge_params_to_session
    session.deep_merge!(params)
  end
  
  def setup_myusa_client
    @myusa_client = OAuth2::Client.new(MYUSA_CLIENT_ID, MYUSA_SECRET_ID, {:site => MYUSA_HOME, :token_url => "/oauth/authorize"})
  end

  def setup_myusa_access_token
    @myusa_access_token = OAuth2::AccessToken.new(@myusa_client, session[:token])
  end

  def create_tasks
    case params['task_type']
    when 'fdic'
      task_params = FdicSearch.build_tasks(params['uid'])
    when 'pbgc'
      task_params = PbgcSearch.build_tasks(params['url'])
    when 'hud'
      task_params = HudSearch.build_tasks(params['uid'])
    when 'ca'
      task_params = CaUnclaimedProperty.build_tasks(params['uid'], params['url'])
    when 'md'
      task_params = MdUnclaimedProperty.build_tasks(params['uid'])
    end
    
    tasks_response = @myusa_access_token.post("/api/tasks", task_params)
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def ca_result_type(type)
    case
    when type == "P"
      content_tag :span, 'P', class: "has-tip tip-left", title: "These are properties sent to the State for safekeeping as required by law. These properties may be claimed through the process outlined on our website. Click on the link in the ID Number column to see the Property Details and access the Claim Form.", "data-tooltip" => nil, "data-width" => 300
    when type == "N"
      content_tag :span, 'N', class: "has-tip tip-left", title: "These are properties still in the possession of the business that will be sent to the State for safekeeping unless the owner contacts the business to recover the property or reactivate the account within the timeframe indicated in the Notice Details. You may contact the business to reactivate or recover the account free of charge. Click on the 'Details' link in the ID Number column to get the Business' Contact Information. Investigators are not allowed to contract with a property owner to help the owner recover properties that a business has reported to the state but the state has yet to receive.", "data-tooltip" => nil, "data-width" => 300
    when type == "I"
      content_tag :span, 'I', class: "has-tip tip-left", title: "These are properties that the business is required to transfer to the State because the owner did not contact the business to recover the property or reactivate the account within the required timeframe. These properties are currently unavailable to be claimed as they are in the process of transferring to the State. When the property is available to be claimed, the 'I' will be replaced with a 'P'. Click on the 'Details' link in the ID Number column to find out more about the 'Interim Details' property.", "data-tooltip" => nil, "data-width" => 300
    end
  end

end

app/views/home/results/_ca.html.haml
- unless @ca_search.try(:results).nil?
  %section#ca
    %p.title{ data: { 'section-title' => true } }
      = link_to "California (#{@ca_search.total})", "#"
    %div.content.clear{ data: { 'section-content' => true } }
      %table.large-12{:summary => "California Unclaimed Money Search Results. First row contains column headers, subsequent rows contain claim information"}
        %thead
          %tr
            %th{:scope =>"col"}
              Name
            %th{:scope =>"col"}
              Address
            %th{:scope =>"col"}
              ID Number
            %th{:scope =>"col"}
              Type
            %th
        %tbody
          - @ca_search.results.each_with_index do |result, index|
            %tr{:scope => "row"}
              %td= result[:name]
              %td= result[:address]
              %td= result[:id]
              %td= ca_result_type(result[:type])
              %td
                = link_to 'Claim', '#', :class => 'small button underline', 'data-reveal-id' => "ca-modal-#{index}"
                %div.reveal-modal.expand{ id: "ca-modal-#{index}" }
                  - if flash["ca-modal-#{index}"] && flash[:success]
                    %div.alert-box.success #{flash[:success]}
                  = button_to 'Save to MyUSA Tasks', add_tasks_path(modal: "ca-modal-#{index}", task_type: 'ca', uid: result[:id], url: result[:href] ),  :class => 'button positive radius right'
                  %h2
                    Start the claim process
                  %ol.lead
                    %li 
                      Write down your Property ID Number 
                      %span.label #{result[:id]}
                      and print the #{link_to 'Property Details', result[:href], target: '_blank', class: 'underline'} screen for your records.
                    %li Fill out a Claim Affirmation Form online or call (800) 992-4647 to have a representative mail the form to you.
                    %li
                      Mail the completed and signed Claim Affirmation Form along with the required documents to:
                      %ul.vcard
                        %li.fn
                          California State Controller's Office
                          Unclaimed Property Division
                        %li.street-address PO Box 942850
                        %li.locality
                          %span.city Sacramento,
                          %span.state CA
                          %span.zip 94250-5873
                    %li Due to the large volume of claims, it may take up to 180 days to process your claim. You may check the status of your claim at any time on the #{link_to 'Claims Status Page', 'https://scoweb.sco.ca.gov/UCP/ClaimStatusSearch.aspx'}.  If you have an outstanding debt with a California state agency, city or county, your unclaimed property payment may be intercepted to pay the debt. Thank you for your patience.                      
                    = link_to raw('&#215;'), "#", class: "close-reveal-modal"
      %div.bottom-buttons
        = button_to 'Search Again', root_path, :class => 'button positive radius right'
        = button_to 'More Results', 'https://scoweb.sco.ca.gov/UCP/', :class => 'button positive radius' if @ca_search.total == 25

app/views/home/results/_fdic.html.haml
%section#fdic
  %p.title{ :data => { 'section-title' => true} }
    -#= link_to "FDIC (#{@fdic_search[:total]})", "#"
  %div.content{ data: { 'section-content' => true } }
    %table.large-12{:summary => "FDIC Unclaimed Money Search Results. First row contains column headers, subsequent rows contain claim information"}
      %thead
        %tr
          %th{:scope =>"col"}
            Reference #
          %th{:scope =>"col"}
            Fund Owner Name
          %th{:scope =>"col"}
            Institution Name
          %th{:scope =>"col"}
            Location
          %th{:scope =>"col"}
            Claim #
          %th{:scope =>"col"}
            Check Date
          %th{:scope =>"col"}
            Check #
          %th
      %tbody
        - @fdic_search[:results].each_with_index do |result, index|
          %tr{:scope => "row"}
            %td= result[:reference_number]
            %td= result[:fund_owner_name]
            %td= result[:institution_name]
            %td= "#{result[:city]}, #{result[:state]}"
            %td= result[:claim_number]
            %td= result[:check_date]
            %td= result[:check_number]
            %td
              = link_to 'Claim', '#', :class => 'small button underline claimLink', 'data-reveal-id' => "fdic-modal-#{index}"
              %div.reveal-modal.expand{ id: "fdic-modal-#{index}" }
                - if flash["fdic-modal-#{index}"] && flash[:success]
                  %div.alert-box.success #{flash[:success]}
                = link_to raw('&#215;'), "#", class: "close-reveal-modal"
                %br
                - if session[:user] != {}
                  = button_to 'Save to MyUSA Tasks', add_tasks_path(modal: "fdic-modal-#{index}", task_type: 'fdic', uid: result[:reference_number]), :class => 'button positive radius right'
                %h2
                  Start the claim process
                %ol.lead
                  %li
                    #{link_to 'Visit FDIC', 'https://www2.fdic.gov/funds/', target: '_blank', class: 'underline'} to find your claim.
                  %li
                    Enter your name to search for your funds.  Write down or print your claim number and reference number. Your reference number should be 
                    %span.label #{result[:reference_number]}.
                  %li
                    Return to the #{link_to 'FDIC Unclaimed Funds website', 'https://www2.fdic.gov/funds/', target: '_blank', class: 'underline'}.
                  %li
                    Follow the instructions at the bottom of the page called 
                    %strong How to claim your funds.
                  %li
                    If you have further inquiries, you may contact #{mail_to 'FDICUnclaimed@FDIC.gov', 'FDIC via E-Mail inquiries', class: "underline"} for the status of a claim.

    = render partial: 'home/results/footer'

app/views/home/results/_footer.html.haml
%div.footer
  %p
    %h2.resultsH2 If you don't see your name in the search results:
  %p
    This app displays the top 25 search results and doesn't cover all possible sources of unclaimed money. It’s possible that you are owed money even if your name doesn’t appear in this list. You may also find more results by searching directly at these sources:
  %ul
    %li.searchHelpList 
      = link_to 'Federal Deposit Insurance Corporation', 'http://www2.fdic.gov/funds/index.asp', :class => 'underline'
    %li.searchHelpList
      = link_to 'Department of Housing and Urban Development', 'http://www.hud.gov/offices/hsg/comp/refunds/', :class => 'underline'
    %li.searchHelpList
      = link_to 'Pension Benefit Guaranty Corporation', 'http://search.pbgc.gov/mp/', :class => 'underline'
    %li.searchHelpList
      = link_to 'Other sources of unclaimed money', 'http://www.usa.gov/Citizen/Topics/Government-Unclaimed-Money.shtml', :class => 'underline'
  %p
    %h2.resultsH2 If you still don't see your name in the results:
  %ul
    %li.searchHelpList You may not be entitled to any unclaimed money from the government.
    %li.searchHelpList You may want to search again later or use a different search term (for example, last name only).
   
  %div.bottom-buttons
    = button_to 'Search Again', root_path, :class => 'button positive radius'

app/views/home/results/_hud.html.haml
%section#hud
  %p.title{ data: { 'section-title' => true } }
    -#= link_to "HUD (#{@hud_search[:total]})", "#"
  %div.content{ data: { 'section-content' => true } }
    %table.large-12{:summary => "HUD Unclaimed Money Search Results. First row contains column headers, subsequent rows contain claim information"}
      %thead
        %tr
          %th{:scope =>"col"}
            Name
          %th{:scope =>"col"}
            Address
          %th{:scope =>"col"}
            Claim date
          %th{:scope =>"col"}
            Case number
          %th
      %tbody
        - @hud_search[:results].each_with_index do |result, index|
          %tr{:scope => "row"}
            %td= result[:name]
            %td= "#{result[:address]} #{result[:city] == ' ' ? '' : result[:city] + ', ' }#{result[:state]} #{result[:zip]}"
            %td= result[:claim_date]
            %td= result[:case_number]
            %td
              = link_to 'Claim', '#', :class => 'small button underline claimLink', 'data-reveal-id' => "hud-modal-#{index}"
              %div.reveal-modal.expand{ id: "hud-modal-#{index}" }
                - if flash["hud-modal-#{index}"] && flash[:success]
                  %div.alert-box.success #{flash[:success]}
                = link_to raw('&#215;'), "#", class: "close-reveal-modal"
                %br
                - if session[:user] != {}
                  = button_to 'Save to MyUSA Tasks', add_tasks_path(modal: "hud-modal-#{index}", task_type: 'hud', uid: result[:case_number]), :class => 'button positive radius right'
                %h2
                  Start the claim process
                %p
                  Call 1-800-697-6967 to get your refund. If your name is not on the list, but you believe that you are owed a refund, call this same toll free number to ask about your status. You can also contact HUD by postal mail using the following address:
                  %ul.vcard
                    %li.fn U.S. Department of Housing and Urban Development
                    %li.street-address P.O. Box 44372
                    %li.locality
                      %span.city Washington,
                      %span.state DC
                      %span.zip 20026-4372
                  %h5 Note
                  All inquiries should include your name, your FHA case number
                  %span.label #{result[:case_number]}
                  , the date that the mortgage was paid-in-full, the property address, and your daytime phone number.
                  %h5 More Info
                  For more information about refunds, read the #{link_to 'Fact Sheet', 'http://www.hud.gov/offices/hsg/comp/refunds/index.cfm', target: '_blank', class: 'underline'}
                  = link_to image_tag('exit_disclaimer.gif', alt: 'Opens in new window'), 'http://www.hud.gov/offices/hsg/comp/refunds/index.cfm'
    = render partial: 'home/results/footer'

app/views/home/results/_md.html.haml
- unless @md_search.try(:results).nil?
  %section#md
    %p.title{ data: { 'section-title' => true } }
      = link_to "Maryland (#{@md_search.total})", "#"
    %div.content{ data: { 'section-content' => true } }
      %table.large-12{:summary => "Maryland Unclaimed Money Search Results. First row contains column headers, subsequent rows contain claim information"}
        %thead
          %tr
            %th{:scope =>"col"}
              Claim
            %th{:scope =>"col"}
              Name
            %th{:scope =>"col"}
              Address
            %th
        %tbody
          - @md_search.results.each_with_index do |result, index|
            %tr{:scope => "row"}
              %td= result[:claim]
              %td= result[:name]
              %td= result[:address]
              %td
                = link_to 'Claim', '#', :class => 'small button underline', 'data-reveal-id' => "md-modal-#{index}"
              %div.reveal-modal.expand{ id: "md-modal-#{index}" }
                - if flash["md-modal-#{index}"] && flash[:success]
                  %div.alert-box.success #{flash[:success]}
                = button_to 'Save to MyUSA Tasks', add_tasks_path(modal: "md-modal-#{index}", task_type: 'md', uid: result[:claim] ), :class => 'button positive radius right'
                %h2
                  Start the claim process
                %ol.lead
                  %li 
                    Print and complete claim form #{link_to 'ST-912', 'http://comptroller.marylandtaxes.com/Public_Services/Unclaimed_Property/static_files/COT-ST912.pdf', target: '_blank', class: 'underline'}. Be sure to indicate you claim number: 
                    %span.label #{result[:claim]}
                  %li
                    Mail the completed and signed Claim Affirmation Form to the Comptroller's Office at the following address:
                    %ul.vcard
                      %li.fn
                        Comptroller of Maryland
                        %br Compliance Division - Unclaimed Property Unit
                      %li.street-address
                        301 West Preston Street
                        Room #310
                      %li.locality
                        %span.city Baltimore,
                        %span.state Maryland
                        %span.zip 21201-2383
                  %h3 More Info
                  %p If you have a question regarding unclaimed property, or would like assistance, please contact the Comptroller of Maryland's Unclaimed Property Unit at 410-767-1700 in the Baltimore metro area, or 1-800-782-7383 nationwide, or e-mail us at #{mail_to 'unclaim@comp.state.md.us'}.
                  = link_to raw('&#215;'), "#", class: "close-reveal-modal"
      %div.bottom-buttons
        = button_to 'Search Again', root_path, :class => 'button positive radius right'
        = button_to 'More Results', 'https://interactive.marylandtaxes.com/individuals/unclaim/default.aspx', :class => 'button positive radius' if @md_search.total == 25

app/views/home/results/_pbgc.html.haml
%section#pbgc
  %p.title{ :data => { 'section-title' => true} }
    -#= link_to "PBGC (#{@pbgc_search[:total]})", "#"
  %div.content{ :data => { 'section-content' => true } }
    %table.large-12{:summary => "PBGC Unclaimed Money Search Results. First row contains column headers, subsequent rows contain claim information"}
      %thead
        %tr
          %th{:scope =>"col"}
            Name
          %th{:scope =>"col"}
            Company Name
          %th{:scope =>"col"}
            Last known address
          %th
      %tbody
        - @pbgc_search[:results].each_with_index do |result, index|
          %tr{:scope => "row"}
            %td= result[:name]
            %td= result[:company]
            %td= result[:last_known_address]
            %td
              = link_to 'Claim', '#', :class => 'small button underline claimLink', 'data-reveal-id' => "pbgc-modal-#{index}"
              %div.reveal-modal.expand{ id: "pbgc-modal-#{index}" }
                - if flash["pbgc-modal-#{index}"] && flash[:success]
                  %div.alert-box.success #{flash[:success]}
                = link_to raw('&#215;'), "#", class: "close-reveal-modal"
                %br
                - if session[:user] != {}
                  = button_to 'Save to MyUSA Tasks', add_tasks_path(modal: "pbgc-modal-#{index}", task_type: 'pbgc', url: result[:claim_url]), :class => 'button positive radius right'
                %h2
                  Start the claim process
                %p.lead
                  Call PBGC toll-free at 1-800-326-LOST. (TTY/TDD users, call the federal relay service toll-free at 1-800-877-8339 and ask to be connected to 1-800-326-LOST) or fill out the #{link_to 'secure form', result[:claim_url], class: 'underline'} and provide the information about the missing participant or beneficiary.
                  %strong Be sure to provide us with a valid telephone number, e-mail address, or mailing address. They need some way to contact you, and any one of those items are suitable. Without that information, we are unable to help the person who may be owed money.
                %p.lead PBGC will contact you shortly after they receive the information.
    = render partial: 'home/results/footer'